### ISSUE TITLE
please add talkback for inclusiveness in the gapps edition 

### ISSUE THREAD

**Issue by animeshahilya** [PixysOS/vendor_pixys#8]

**Comment by tesla59** [comment]
@animeshahilya But why

**Comment by animeshahilya** [comment]
because there are people who are blind and are using this firmwhere. if we include this, it will help them from the setup screen it self. and they can use it indipenduntly.

**Comment by shreejoy** [comment]
@animeshahilya Thanks for your information. I will pass this to the concerned persons

**Comment by animeshahilya** [comment]
you are welcome sir

**Comment by Darkstar085** [comment]
Useless.. If they r using custom roms then they should know how to use it..

**Comment by animeshahilya** [comment]
they can not see sir, and talkback speaks for them. they can install itt from playstore, but the playstor can't be used from the setup screen. that is how the things are. if u don't want to make then it is fine. but if u don't want more  users for this firmwhere, then only ignore this.
